box_art_dir = "/home/florian/.config/rofi-games/box-art"

[[entries]]
title = "01-Script Game"
launch_command = "/home/florian/.config/hypr/UserScripts/EditScriptGame.sh"
path_box_art = "Neo.png"

[[entries]]
title = "Ankama Launcher"
launch_command = "/home/florian/Applications/Ankama_4a46072423842bfe366d20988ab1bba1.AppImage --no-sandbox %U"
path_box_art = "ankama.png"

[[entries]]
title = "Vortex"
launch_command = "/home/florian/Applications/NexusMods.App.x86_64_3315cb0ddb1ababf804f21649039c4e4.AppImage %u"
path_box_art = "vortex.png"

[[entries]]
title = "Heroic Launcher"
launch_command = "/home/florian/Applications/Heroic-2.16.0-linux-x86_64_16aa4406855fc66e3c13159a03592254.AppImage --no-sandbox %U"
path_box_art = "heroic.png"

[[entries]]
title = "Battle.net"
launch_command = "xdg-open heroic://launch/sideload/oMmBBJ5V9e7tDXPoyCpZiy"
path_box_art = "battle.jpg"

[[entries]]
title = "Parsec"
launch_command = "/usr/bin/parsecd %u"
path_box_art = "parsec.png"


[[entries]]
title = "Magic The Gathering"
launch_command = "steam steam://rungameid/2141910"
path_box_art = "Magic.jpg" 
